# Generated by Django 4.2.3 on 2023-11-22 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_category', models.CharField(max_length=200)),
                ('product_sub_category', models.CharField(max_length=200)),
                ('product_brand', models.CharField(max_length=200)),
                ('product_price', models.FloatField()),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='pictures/')),
       
            ]
        )
    ]
